use _HAVE_ARGCOMPLETE flag for import argcomplete
Setting autocomplete to None if it can not be imported from argcomplete
now causes mypy to fail with

> src/packagename/cli.py:17: error: Incompatible types in assignment (expression has type "None", variable has type "CompletionFinder")  [assignment]

I'm not aware of a way to add an Optional type hint to autocomplete, so
instead of assigning None to it, add a flag named _HAVE_AUTOCOMPLETE to
track whether it has been imported.

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>