fix: pass _PROG_NAME to _build_argument_parser
Instead of adding it in _build_argument_parser, which causes

> TypeError: argparse.ArgumentParser() got multiple values for keyword argument 'prog'

Fixes: d18737ffec72 ("create and use _PROG_NAME constant")
Signed-off-by: Kevin Locke <kevin@kevinlocke.name>